[package]
name = "muzic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soloud = { git = "https://github.com/moalyousef/soloud-rs" }
rand = "0.8"
